apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
spec:
  selector:
    matchLabels:
      app: selenium
  replicas: 2
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
      - name: selenium
        image: ruudgong/selenium:latest
        ports:
        - containerPort: 8080
